remote_theme: just-the-docs/just-the-docs

title: hitec Dev
description: Hitec 가 해보는 개발
baseurl: "/"
url: "https://hitec2022.github.io"

color_scheme: dark

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-6J3Z9CH88V
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

# Aux links for the upper right navigation
aux_links:
  "Hitec GitHub":
    - "//github.com/hitec2022"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
#footer_content: "hitec email : lightinglake@hanmail.net"

# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
